name: Test GDExtension

on:
  workflow_call:
    inputs:
      platform:
        description: 'Target platform'
        required: true
        type: string
      arch:
        description: 'Target architecture'
        required: true
        type: string
      os:
        description: 'Runner OS'
        required: true
        type: string
      float-precision:
        description: 'Float precision'
        required: false
        type: string
        default: 'single'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Target platform'
        required: false
        type: choice
        options:
          - linux
          - windows
          - macos
        default: 'linux'
      arch:
        description: 'Target architecture'
        required: false
        type: choice
        options:
          - x86_64
          - x86_32
          - arm64
          - universal
        default: 'x86_64'
      float-precision:
        description: 'Float precision'
        required: false
        type: choice
        options:
          - single
          - double
        default: 'single'

env:
  LIBNAME: inventory-system

jobs:
  test:
    runs-on: ${{ inputs.os || 'ubuntu-22.04' }}
    
    steps:
      # Clone this repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # Setup dependencies
      - name: Setup godot-cpp
        uses: ./godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ inputs.platform || 'linux' }}
          em-version: 3.1.62

      # Restore cache for faster builds
      - name: Restore .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-restore
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: test_${{ inputs.platform || 'linux' }}_${{ inputs.arch || 'x86_64' }}_${{ inputs.float-precision || 'single' }}

      # Build tests
      - name: Build Tests
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
        run: |
          scons tests=yes target=template_debug platform=${{ inputs.platform || 'linux' }} arch=${{ inputs.arch || 'x86_64' }} precision=${{ inputs.float-precision || 'single' }}

      # Save cache
      - name: Save .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-save
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: test_${{ inputs.platform || 'linux' }}_${{ inputs.arch || 'x86_64' }}_${{ inputs.float-precision || 'single' }}

      # Run tests (Linux/macOS)
      - name: Run Tests (Unix)
        if: ${{ (inputs.platform || 'linux') != 'windows' }}
        shell: sh
        run: |
          cd ${{ github.workspace }}
          chmod +x bin/${{ inputs.platform || 'linux' }}/inventory_tests
          ./bin/${{ inputs.platform || 'linux' }}/inventory_tests

      # Run tests (Windows)
      - name: Run Tests (Windows)
        if: ${{ (inputs.platform || 'linux') == 'windows' }}
        shell: pwsh
        run: |
          cd ${{ github.workspace }}
          .\bin\windows\inventory_tests.exe

      # Upload test results as artifacts (optional)
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ inputs.platform || 'linux' }}-${{ inputs.arch || 'x86_64' }}-${{ inputs.float-precision || 'single' }}
          path: |
            ${{ github.workspace }}/bin/${{ inputs.platform || 'linux' }}/inventory_tests*
          retention-days: 7